name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create the webhook.js file
        run: |
          echo 'const webhookURL = "${{ secrets.WEBHOOK_URL }}";' > webhook.js

      - name: Prepare the deploy directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/deploy
          rsync -av --progress --exclude='deploy' . $GITHUB_WORKSPACE/deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
